import logging
import os
from datetime import datetime, timezone, timedelta

from config import OBSIDIAN_LOG_PATH

logger = logging.getLogger(__name__)

MYT = timezone(timedelta(hours=8))

_LOG_HEADER = """# Investment Log

> Auto-generated by Investment Monitoring Agent
> Goal: RM200/month passive income for server costs
> Agent: `/home/penyahpepijat/claude/investment-agent/`

---

"""


def ensure_log_file() -> None:
    os.makedirs(os.path.dirname(OBSIDIAN_LOG_PATH), exist_ok=True)
    if not os.path.exists(OBSIDIAN_LOG_PATH):
        with open(OBSIDIAN_LOG_PATH, "w", encoding="utf-8") as f:
            f.write(_LOG_HEADER)


def log_dividend_received(reit_name: str, amount: float, date: str) -> None:
    ensure_log_file()
    entry = (
        f"\n## Dividend Received — {date}\n\n"
        f"- **REIT:** {reit_name}\n"
        f"- **Amount:** RM{amount:.2f}\n\n"
        f"---\n"
    )
    try:
        with open(OBSIDIAN_LOG_PATH, "a", encoding="utf-8") as f:
            f.write(entry)
    except Exception as e:
        logger.error("Failed to log dividend to Obsidian: %s", e)


def log_portfolio_snapshot(summary: dict) -> None:
    ensure_log_file()
    now = datetime.now(MYT).strftime("%Y-%m-%d %H:%M MYT")

    rows = []
    for h in summary["holdings"]:
        price_str = f"{h['current_price']:.4f}" if h["current_price"] else "N/A"
        rows.append(
            f"| {h['name']} | {price_str} | {h['div_yield'] * 100:.2f}% "
            f"| {h['monthly_income']:.2f} | {h['gain_loss_pct']:+.1f}% |"
        )

    table = "\n".join([
        "| REIT | Price (RM) | Yield | Monthly Income (RM) | G/L % |",
        "|------|-----------|-------|---------------------|-------|",
        *rows,
    ])

    entry = (
        f"\n## Portfolio Snapshot — {now}\n\n"
        f"{table}\n\n"
        f"**Portfolio Value:** RM{summary['total_value']:.2f}  \n"
        f"**Monthly Income:** RM{summary['total_monthly_income']:.2f}  \n"
        f"**Progress to Target:** {summary['progress_pct']:.1f}%  \n\n"
        f"---\n"
    )

    try:
        with open(OBSIDIAN_LOG_PATH, "a", encoding="utf-8") as f:
            f.write(entry)
    except Exception as e:
        logger.error("Failed to log portfolio snapshot to Obsidian: %s", e)
